import { headers } from "next/headers";
import ls from "localstorage-slim";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const getMsisdn = async () => {
    const msisdn = await headers();
    ls.set("magicboxtv", msisdn["msisdn"], { encrypt: true });
  }

  getMsisdn()

  return (
    <html lang="en">
      <body
        className={`bg-gray-950 select-none`}
      >
        {children}
      </body>
    </html>
  );
}
